/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.extension.aggregator.internal.routes;

import org.joda.time.DateTime;


/**
 * Attributes with information regarding the containing aggregator and the aggregated elements
 *
 * @since 1.0
 */
public class AggregatorAttributes {

  /**
   * The group Id. It's value comes from the event's message correlationId.
   * If the aggregator does not aggregate by correlationId, then this field will be an autogenerated value for the
   * current aggregated group.
   */
  private String groupId;

  /**
   * The time in which the first aggregated value arrived.
   */
  private long firstValueArrivalTime;

  /**
   * The time in which the last aggregated value arrived.
   */
  private long lastValueArrivalTime;

  /**
   * A boolean value indicating if the aggregated group is complete
   */
  private boolean isGroupComplete;

  public AggregatorAttributes() {
    this.isGroupComplete = false;
  }

  public AggregatorAttributes(String groupId, long firstValueArrivalTime, long lastValueArrivalTime, boolean isGroupComplete) {
    this.groupId = groupId;
    this.firstValueArrivalTime = firstValueArrivalTime;
    this.lastValueArrivalTime = lastValueArrivalTime;
    this.isGroupComplete = isGroupComplete;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public void setFirstValueArrivalTime(long firstValueArrivalTime) {
    this.firstValueArrivalTime = firstValueArrivalTime;
  }

  public void setLastValueArrivalTime(long lastValueArrivalTime) {
    this.lastValueArrivalTime = lastValueArrivalTime;
  }

  public void setGroupComplete() {
    isGroupComplete = true;
  }

  public String getGroupId() {
    return groupId;
  }

  public long getFirstValueArrivalTime() {
    return firstValueArrivalTime;
  }

  public long getLastValueArrivalTime() {
    return lastValueArrivalTime;
  }

  public boolean isGroupComplete() {
    return isGroupComplete;
  }
}
