projectType: extension
mavenAdditionalArgs: -DminVersion=4.3.0
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DruntimeVersion=4.8.5 # TODO: Remove this runtimeVersion once we have a new parent version with MTF
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DminVersion=4.6.0 -Dtest=none -DfailIfNoTests=false
