/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.extension.aggregator.api;


import org.mule.runtime.extension.api.annotation.param.Parameter;

import java.util.Date;

/**
 * Attributes with information regarding the containing aggregator and the aggregated elements
 *
 * @since 1.0
 */
public class AggregationAttributes {

  /**
   * The aggregation Id. It's value comes from the event's message correlationId.
   * If the aggregator does not aggregate by correlationId, then this field will be an autogenerated value for the
   * current aggregated group.
   */
  @Parameter
  private String aggregationId;

  /**
   * The time in which the first aggregated value arrived.
   */
  @Parameter
  private long firstItemArrivalTime;

  /**
   * The time in which the last aggregated element arrived.
   */
  @Parameter
  private long lastItemArrivalTime;

  /**
   * A boolean value indicating if the aggregated group is complete
   */
  @Parameter
  private boolean isGroupComplete;

  public AggregationAttributes() {
    this.isGroupComplete = false;
  }

  public AggregationAttributes(String aggregationId, long firstItemArrivalTime, long lastItemArrivalTime,
                               boolean isGroupComplete) {
    this.aggregationId = aggregationId;
    this.firstItemArrivalTime = firstItemArrivalTime;
    this.lastItemArrivalTime = lastItemArrivalTime;
    this.isGroupComplete = isGroupComplete;
  }

  public void setAggregationId(String aggregationId) {
    this.aggregationId = aggregationId;
  }

  public void setFirstItemArrivalTime(long firstItemArrivalTime) {
    this.firstItemArrivalTime = firstItemArrivalTime;
  }

  public void setLastItemArrivalTime(long lastItemArrivalTime) {
    this.lastItemArrivalTime = lastItemArrivalTime;
  }

  public void setGroupComplete() {
    isGroupComplete = true;
  }

  public String getAggregationId() {
    return aggregationId;
  }

  public Date getFirstItemArrivalTime() {
    return new Date(firstItemArrivalTime);
  }

  public Date getLastItemArrivalTime() {
    return new Date(lastItemArrivalTime);
  }

  public boolean isGroupComplete() {
    return isGroupComplete;
  }
}
